
version: '3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  keycloak:
    image: steedos/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HTTP_ENABLED=true
      - KC_PROXY=passthrough
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HOSTNAME_STRICT=false
      - KC_SPI_THEME_DEFAULT=steedos
    command:
      - "start"
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local